---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: raffle-service
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: raffle-service@sha256:7acc440d738e988ea832dd79554ebbcb743f4bbb3beafa937f92e93659cc51b1
        namespace: redhat-raffle
      name: latest
