DROP TABLE IF EXISTS ATTENDEE CASCADE;
DROP TABLE IF EXISTS EVENT CASCADE;

CREATE TABLE ATTENDEE (
	ID INTEGER NOT NULL,
	FIRST_NAME CHARACTER VARYING(256) NOT NULL,
	LAST_NAME CHARACTER VARYING(256) NOT NULL,
	SCANNED_VALUE CHARACTER VARYING(256) NOT NULL,
	PRIMARY KEY ( ID )
);

CREATE TABLE EVENT (
	ID INTEGER NOT NULL,
	EVENT_NAME CHARACTER VARYING(256) NOT NULL,
	EVENT_CITY CHARACTER VARYING(256) NOT NULL,
	EVENT_COUNTRY CHARACTER(256) NOT NULL,
	PRIMARY KEY ( ID )
);
