apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: fabric8
    version: ${project.version}
spec:
  template:
    spec:
      containers:
        - env:
            - name: VIRTUALLAYER_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: virtuallayer-secret
                   key: username
            - name: VIRTUALLAYER_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: virtuallayer-secret
                   key: password
            - name: VDB_NAME
              value: "reservation"
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
            - name: BOOKING_STATE_SERVICE_GET_URL
              value: "http://booking-state-service-hotelbooking.apps.46.4.112.21.xip.io/getbookingstate"
            - name: BOOKING_STATE_SERVICE_DELETE_URL
              value: "http://booking-state-service-hotelbooking.apps.46.4.112.21.xip.io/deletebookingstate"